FROM own3dh2so4/base-jenkins-slave:1.0
MAINTAINER David Garcia <david.garcia.alvarez.93@gmail.com>

# Download and install Java openjdk8
RUN apk --update --no-cache add openjdk8 && \
  rm -rf /var/cache/apk/*